### ISSUE TITLE
HDBC-mysql--6.6.1 not adapted to new setup?

### ISSUE THREAD

**Issue by andrewufrank** [ryantm/hdbc-mysql#18] opened 2015-11-29 14:24 UTC
i got today with 7.10.2 the following error msg. thank you for fixing!
````
tmp/HDBC-mysql-0.6.6.1-3715/HDBC-mysql-0.6.6.1/dist/setup/setup.hs:31:7:
Couldn't match type ‘IO (Maybe FilePath)’
with ‘ProgramSearchPath -> IO (Maybe FilePath)’
Expected type: IO (Maybe FilePath)
-> (Maybe FilePath -> IO (Maybe FilePath))
-> ProgramSearchPath
-> IO (Maybe FilePath)
Actual type: IO (Maybe FilePath)
-> (Maybe FilePath -> IO (Maybe FilePath)) -> IO (Maybe FilePath)
In a stmt of a 'do' block:
mysql_config <- findProgramOnPath "mysql_config" verbosity
In the expression:
do { mysql_config <- findProgramOnPath "mysql_config" verbosity;
mysql_config5 <- findProgramOnPath "mysql_config5" verbosity;
return (mysql_config `mplus` mysql_config5) }
In the ‘programFindLocation’ field of a record
)
````

**Comment by ocharles** [comment] 2016-01-04 13:02
Duplicate of https://github.com/bos/hdbc-mysql/issues/17

**Closed** 2016-08-25 17:17 UTC
